--- 
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://localhost:30001
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 93621ec5c0eb3001be69
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: techvidcloud
            teams:
            - admin
            - awteam