apiVersion: v1
kind: Secret
metadata:
  name: prom-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:tiwarisanjay/prometheus-grafana-install