apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - overlays/repository.yaml

patchesStrategicMerge:
  - overlays/nodeport.yaml
  - overlays/argocd-cm.yaml
  - overlays/argocd-rbac-cm.yaml

namespace: argocd