apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiwarisanjay/application-charts.git
    path: test
    targetRevision: HEAD
    helm:
      valueFiles:
      - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: testns 
  syncPolicy:
    retry:
      limit: 2
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
      - Replace=true # It will recreate the resources if deleted outside. 