apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiwarisanjay/prometheus-grafana-install.git
    targetRevision: HEAD
    path: kubernetes-prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring