apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiwarisanjay/argocd-dex.git
    targetRevision: HEAD
    path: app-declaration
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
      automated:
        selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).